language: ruby
rvm:
  - 2.4.1
branches:
  only:
  - master
before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
env:
  - github_token="c8e722059de230a2809afbec3d68fde90749c1c2"
script: ./assets/cibuild
deploy:
  provider: pages
  skip_cleanup: true
  github_token: c8e722059de230a2809afbec3d68fde90749c1c2
  local_dir: _site
  keep-history: true
  on:
    branch: master
    target_branch: gh-pages
exclude: [vendor]
sudo: false