#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://github.com/median-lab/median-lab.github.io.git --branch gh-pages _site
# git remote set-url gh-pages git@github.com:median-lab/median-lab.github.io.git
# git clone $github_token@github.com:median-lab/median-lab.github.io.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
# git push --force origin gh-pages
git push --force https://$github_token@github.com/median-lab/median-lab.github.io.git origin gh-pages